name: playwright

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11", "3.12", "3.13"]
        runner: [ubuntu-latest,ubuntu-24.04-arm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install playwright
        run: |
          pip install playwright
          playwright install --with-deps
          
